# Generated by Django 6.0 on 2026-02-28 13:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_created_at_student_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cert_type', models.CharField(choices=[('COMPLETION', 'Certificate of Completion'), ('ACHIEVEMENT', 'Certificate of Achievement'), ('EXCELLENCE', 'Certificate of Excellence'), ('ATTENDANCE', 'Certificate of Attendance'), ('PARTICIPATION', 'Certificate of Participation'), ('OTHER', 'Other')], default='COMPLETION', max_length=20, verbose_name='Certificate Type')),
                ('file', models.FileField(upload_to='certificates/%Y/', verbose_name='Certificate File (PDF/Image)')),
                ('description', models.TextField(blank=True, null=True)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_date'],
            },
        ),
    ]
