# Generated by Django 6.0 on 2026-01-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
