# Generated by Django 6.0 on 2026-02-28 14:26

import pyuploadcare.dj.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=pyuploadcare.dj.models.FileField(verbose_name='Certificate File'),
        ),
    ]
