# Generated by Django 6.0 on 2026-01-14 16:43

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classroom_id_alter_subject_id'),
        ('students', '0003_alter_student_options_student_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-date_created', 'full_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='students/documents/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='students_st_email_e271bc_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['registration_number'], name='students_st_registr_23d894_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['classroom', 'admission_year'], name='students_st_classro_d53d5c_idx'),
        ),
    ]
