# Generated by Django 6.0 on 2026-01-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_options_student_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_email_e271bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_registr_23d894_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_classro_d53d5c_idx',
        ),
        migrations.AlterField(
            model_name='student',
            name='documents',
            field=models.FileField(blank=True, default=1, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default=1, upload_to='students/'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_updated',
        ),
    ]
