# Generated by Django 6.0 on 2026-02-28 15:32

import django.db.models.deletion
import pyuploadcare.dj.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('exams', '0001_initial'),
        ('students', '0004_alter_certificate_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', pyuploadcare.dj.models.FileField(blank=True, null=True, verbose_name='Assignment File (PDF/Doc)')),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft'), ('CLOSED', 'Closed')], default='PUBLISHED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classes.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='classes.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', pyuploadcare.dj.models.FileField(verbose_name='Submission File')),
                ('comment', models.TextField(blank=True, verbose_name='Student Comment')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('LATE', 'Late Submission'), ('GRADED', 'Graded'), ('RETURNED', 'Returned for Revision')], default='SUBMITTED', max_length=10)),
                ('marks', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, verbose_name='Teacher Feedback')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
