# Generated by Django 5.2 on 2026-01-10 21:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+255123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('relationship', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Guardian'), ('OTHER', 'Other')], default='GUARDIAN', max_length=20, verbose_name='Relationship')),
                ('address', models.TextField(verbose_name='Address')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Occupation')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='parents/profile_pictures/', verbose_name='Profile Picture')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('students', models.ManyToManyField(blank=True, related_name='parents', to='students.student', verbose_name='Children')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'ordering': ['full_name'],
                'permissions': [('view_parent_dashboard', 'Can view parent dashboard'), ('view_child_attendance', 'Can view child attendance'), ('view_child_results', 'Can view child results'), ('view_child_fees', 'Can view child fees'), ('view_school_announcements', 'Can view school announcements')],
            },
        ),
    ]
